apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
      tier: server
  template:
    metadata:
      labels:
        app: hello-world
        tier: server
    spec:
      containers:
        - name: hello-world
          image: allohamora/hello-world:7.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: hello-world-secret
            - configMapRef:
                name: hello-world-config-map
          env:
            - name: PORT
              value: "3000"
