secretGenerator:
  - name: hello-world-secret
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
resources:
  - postgres.stateful-set.yml
  - postgres.service.yml
  - hello-world.config-map.yml
  - hello-world.deployment.yml
  - hello-world.service.yml
