apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: hello-world
spec:
  type: ClusterIP
  selector:
    app: hello-world
    tier: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
