version: "3.9"
services:
  nginx:
    image: nginx:1.21.6
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf/
  app:
    build: .
    ports:
      - 3000:3000
