version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2022-03-24T00-43-44Z.fips
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    env_file:
      - .env
    command: server --console-address ":9001" /data
volumes:
  minio-data:
