version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2022-03-24T00-43-44Z.fips
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: example
      MINIO_ROOT_PASSWORD: example
volumes:
  minio-data:
