version: "3.9"

services:
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass ${REDIS_PASS}
    volumes:
      - redis-data:/data
  sender:
    build:
      context: .
      dockerfile: sender.Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - redis
  consumer-1: &consumer
    build:
      context: .
      dockerfile: consumer.Dockerfile
    env_file:
      - .env
    environment:
      - CONSUMER_ID=1
    depends_on:
      - redis
  consumer-2:
    <<: *consumer
    environment:
      - CONSUMER_ID=2

volumes:
  redis-data:
