version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.9.25-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  rabbitmq-data:
  rabbitmq-log:
